apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        #imagePullPolicy: Never
        image: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysqldata
            mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: mysql-pass3
                 key: password

      volumes:

        - name: mysqldata
          persistentVolumeClaim:
            claimName: mysqldata-claim



---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqldata
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /opt/mysql/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldata-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass3
type: Opaque
data:
  password: UGFzc3dvcmQhCg==
