---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqldata
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /opt/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldata-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
