apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:

            - mountPath: /var/cache/nginx
              name: varlog

            - mountPath: /var/log
              name: varcache

            - mountPath: /var/log/nginx
              name: varlog
              subPath: nginx

            - mountPath: /tmp
              name: tmp

            # - name: wwwdata
            #   mountPath: /var/wordpress

            #- name: data
            #  mountPath: /var/www



            - name: nginx-conf-file
              readOnly: true
              mountPath: /etc/nginx/conf.d/site.conf
              subPath: site.conf

            - name: nginx-conf-file
              readOnly: true
              mountPath: /var/www/index.php
              subPath: index.php
      volumes:
      - name: tmp
        emptyDir: {}

      - name: varlog
        emptyDir: {}

      - name: varcache
        emptyDir: {}

      - name: nginx-conf-file
        configMap:
          defaultMode: 420
          name: nginx-config


---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
